version: '3.5'
services:
  php:
    env_file: .env
    build:
      context: docker/images/php-fpm7.3
      args:
        UID: ${HOST_UID}
        TIMEZONE: ${TIMEZONE}
        APPLICATION_WEB_PORT: ${APPLICATION_WEB_PORT}
    volumes:
      - ${RELATIVE_APP_PATH}:/var/www/html
    ports:
      - ${APPLICATION_WEB_PORT}:8000